sudo: required

language: generic

services:
  - docker

before_install:
  - VERSION=$(cat build_versions)
  - PACKAGE=powershell_${VERSION}-1.ubuntu.18.04_amd64.deb
  - PACKAGE_URL=https://github.com/PowerShell/PowerShell/releases/download/v${VERSION}/${PACKAGE}
  - echo $PACKAGE_URL

script:
#  - echo $version
  - docker build --build-arg PS_PACKAGE_URL=$PACKAGE_URL .
#  - docker build --build-arg PS_VERSION=$(cat build_versions) --build-arg PS_PACKAGE --build-arg PS_PACKAGE_URL .
#  - docker build .
